// src/data/servicesData.js
const servicesData = {
  en: [
    { id: 1, title: "Dry Cleaning", category: "dry-cleaning", description: "Expert care for suits and delicate fabrics using eco-friendly solvents", price: "From 6 QAR", icon: "🧥", image: "./home/dryCleaning.jpg" },
    { id: 2, title: "Executive Pressing", category: "pressing", description: "Crisp finishes for business attire with precision steam technology", price: "From 3 QAR", icon: "👔", image: "./home/exectivePressing.jpg" },
    { id: 3, title: "Couture Care", category: "specialty", description: "Hand-cleaning for designer garments and delicate fabrics", price: "From 7 QAR", icon: "👗", image: "./home/care.jpg" },
    { id: 4, title: "Bisht Restoration", category: "specialty", description: "Traditional cleaning and pressing for Qatari formal wear", price: "From 25 QAR", icon: "🕌", image: "./home/resturation.jpg" },
    { id: 5, title: "Express Service", category: "express", description: "3-hour turnaround for urgent garment needs", price: "+30% Premium", icon: "⚡", image: "./home/sehedulePickup.jpg" },
    { id: 6, title: "Fragrance Infusion", category: "addon", description: "Luxury scent options for your garments", price: "5 QAR", icon: "🌸", image: "./home/fragrance.jpg" },
    { id: 7, title: "Dishdasha", category: "traditional", description: "Professional care for men's traditional Qatari garment", price: "From 4 QAR", icon: "👳‍♂️", image: "./services/dishdasha.webp" },
    { id: 8, title: "Child Dishdasha", category: "traditional", description: "Specialized care for children's traditional garments", price: "From 3 QAR", icon: "👦", image: "./services/child_dishdasha.jpg" },
    { id: 9, title: "Bisht", category: "traditional", description: "Premium care for ceremonial cloak with gold detailing", price: "From 25 QAR", icon: "🪔", image: "./services/bisht.jpg" },
    { id: 10, title: "Ghutra", category: "traditional", description: "Gentle cleaning for traditional headwear", price: "From 3 QAR", icon: "🧕", image: "./services/ghutra.jpg" },
    { id: 11, title: "Kurta", category: "traditional", description: "Care for traditional South Asian tunic", price: "From 4 QAR", icon: "👘", image: "./services/kurta.jpg" },
    { id: 12, title: "Kurta Pyjama (Set)", category: "traditional", description: "Complete set cleaning for traditional attire", price: "From 6 QAR", icon: "👖", image: "./services/kurtaPajama.jpg" },
    { id: 13, title: "Kameez", category: "traditional", description: "Professional care for traditional long shirts", price: "From 4 QAR", icon: "👕", image: "./services/kameez.jpg" },
    { id: 14, title: "Jalabiya", category: "traditional", description: "Specialized care for flowing traditional gowns", price: "From 6 QAR", icon: "👚", image: "./services/jalabiya.jpg" },
    { id: 15, title: "Abaya", category: "traditional", description: "Professional cleaning for everyday abayas", price: "From 10 QAR", icon: "🧕", image: "./services/abaya.jpg" },
    { id: 16, title: "Abaya Special", category: "traditional", description: "Premium care for embellished abayas", price: "From 12 QAR", icon: "✨", image: "./services/abaya_special.jpg" },
    { id: 17, title: "Hijab", category: "traditional", description: "Delicate cleaning for headscarves", price: "From 3 QAR", icon: "🧣", image: "./services/hijab.png" },
    { id: 18, title: "Gent Suit (3pcs)", category: "dry-cleaning", description: "Complete care for 3-piece suits", price: "From 12 QAR", icon: "👔", image: "./services/gent_suit.jpg" },
    { id: 19, title: "Dress (Short)", category: "dry-cleaning", description: "Care for cocktail and summer dresses", price: "From 10 QAR", icon: "👗", image: "./services/dress.jpg" },
    { id: 20, title: "Dress (Long)", category: "dry-cleaning", description: "Specialized care for evening gowns", price: "From 15 QAR", icon: "👰", image: "./services/dressLong.jpg" },
    { id: 21, title: "Overcoat", category: "dry-cleaning", description: "Winter coat cleaning and preservation", price: "From 11 QAR", icon: "🧥", image: "./services/overcoat.jpg" },
    { id: 22, title: "Military Uniform", category: "specialty", description: "Regimental standard cleaning and pressing", price: "From 9 QAR", icon: "🎖️", image: "./services/military_suite.jpg" },
    { id: 23, title: "Blouse (Special)", category: "specialty", description: "Delicate care for embellished tops", price: "From 4 QAR", icon: "👚", image: "./services/blouse.jpg" },
    { id: 24, title: "Bath Robe", category: "specialty", description: "Deep cleaning for plush bathrobes", price: "From 4 QAR", icon: "🛁", image: "./services/bathrob.jpg" },
  ],
  ar: [
    { id: 1, title: "التنظيف الجاف", category: "dry-cleaning", description: "عناية متخصصة للبدلات والأقمشة الحساسة باستخدام مذيبات صديقة للبيئة", price: "ابتداءً من 6 ريال", icon: "🧥", image: "./home/dryCleaning.jpg" },
    { id: 2, title: "الكي التنفيذي", category: "pressing", description: "تشطيبات دقيقة للملابس الرسمية باستخدام تقنية البخار المتقدمة", price: "ابتداءً من 3 ريال", icon: "👔", image: "./home/exectivePressing.jpg" },
    { id: 3, title: "عناية الأزياء الفاخرة", category: "specialty", description: "تنظيف يدوي للملابس المصممة والأقمشة الحساسة", price: "ابتداءً من 7 ريال", icon: "👗", image: "./home/care.jpg" },
    { id: 4, title: "ترميم البشت", category: "specialty", description: "تنظيف وكي تقليدي للأزياء الرسمية القطرية", price: "ابتداءً من 25 ريال", icon: "🕌", image: "./home/resturation.jpg" },
    { id: 5, title: "خدمة عاجلة", category: "express", description: "معالجة خلال 3 ساعات لاحتياجات الملابس المستعجلة", price: "بزيادة 30٪", icon: "⚡", image: "./home/sehedulePickup.jpg" },
    { id: 6, title: "إضافة عطر", category: "addon", description: "خيارات عطرية فاخرة لملابسك", price: "5 ريال", icon: "🌸", image: "./home/fragrance.jpg" },
    { id: 7, title: "الدشداشة", category: "traditional", description: "عناية احترافية للزي القطري التقليدي الرجالي", price: "ابتداءً من 4 ريال", icon: "👳‍♂️", image: "./services/dishdasha.webp" },
    { id: 8, title: "دشداشة الأطفال", category: "traditional", description: "عناية متخصصة لأزياء الأطفال التقليدية", price: "ابتداءً من 3 ريال", icon: "👦", image: "./services/child_dishdasha.jpg" },
    { id: 9, title: "بشت", category: "traditional", description: "عناية مميزة للبشت الاحتفالي بتفاصيل ذهبية", price: "ابتداءً من 25 ريال", icon: "🪔", image: "./services/bisht.jpg" },
    { id: 10, title: "الغطرة", category: "traditional", description: "تنظيف ناعم للغطاء التقليدي للرأس", price: "ابتداءً من 3 ريال", icon: "🧕", image: "./services/ghutra.jpg" },
    { id: 11, title: "الكورتا", category: "traditional", description: "عناية للزي التقليدي الجنوب آسيوي", price: "ابتداءً من 4 ريال", icon: "👘", image: "./services/kurta.jpg" },
    { id: 12, title: "طقم كورتا بيجاما", category: "traditional", description: "تنظيف شامل للزي التقليدي", price: "ابتداءً من 6 ريال", icon: "👖", image: "./services/kurtaPajama.jpg" },
    { id: 13, title: "القميص (كميز)", category: "traditional", description: "عناية احترافية للقميص الطويل التقليدي", price: "ابتداءً من 4 ريال", icon: "👕", image: "./services/kameez.jpg" },
    { id: 14, title: "جلابية", category: "traditional", description: "عناية متخصصة للفساتين التقليدية الفضفاضة", price: "ابتداءً من 6 ريال", icon: "👚", image: "./services/jalabiya.jpg" },
    { id: 15, title: "عباية", category: "traditional", description: "تنظيف احترافي للعبايات اليومية", price: "ابتداءً من 10 ريال", icon: "🧕", image: "./services/abaya.jpg" },
    { id: 16, title: "عباية مميزة", category: "traditional", description: "رعاية فاخرة للعبايات المطرزة", price: "ابتداءً من 12 ريال", icon: "✨", image: "./services/abaya_special.jpg" },
    { id: 17, title: "الحجاب", category: "traditional", description: "تنظيف لطيف للأوشحة الرأسية", price: "ابتداءً من 3 ريال", icon: "🧣", image: "./services/hijab.png" },
    { id: 18, title: "بدلة رجال (3 قطع)", category: "dry-cleaning", description: "رعاية شاملة للبدل الثلاث قطع", price: "ابتداءً من 12 ريال", icon: "👔", image: "./services/gent_suit.jpg" },
    { id: 19, title: "فستان (قصير)", category: "dry-cleaning", description: "عناية لفساتين الكوكتيل والصيف", price: "ابتداءً من 10 ريال", icon: "👗", image: "./services/dress.jpg" },
    { id: 20, title: "فستان (طويل)", category: "dry-cleaning", description: "عناية متخصصة لفساتين السهرة", price: "ابتداءً من 15 ريال", icon: "👰", image: "./services/dressLong.jpg" },
    { id: 21, title: "معطف", category: "dry-cleaning", description: "تنظيف وحفظ للمعاطف الشتوية", price: "ابتداءً من 11 ريال", icon: "🧥", image: "./services/overcoat.jpg" },
    { id: 22, title: "زي عسكري", category: "specialty", description: "تنظيف وكي حسب المعيار العسكري", price: "ابتداءً من 9 ريال", icon: "🎖️", image: "./services/military_suite.jpg" },
    { id: 23, title: "بلوزة (مميزة)", category: "specialty", description: "رعاية دقيقة للبلوزات المطرّزة", price: "ابتداءً من 4 ريال", icon: "👚", image: "./services/blouse.jpg" },
    { id: 24, title: "روب حمام", category: "specialty", description: "تنظيف عميق للروباش الناعمة", price: "ابتداءً من 4 ريال", icon: "🛁", image: "./services/bathrob.jpg" },
  ],
};

export default servicesData;